server:
  port: 8088
spring:
  application:
    name: graph
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.203:3306/graph?characterEncoding=utf8&useSSL=false&useAffectedRows=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: ktwlrjcs2018
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  logic-not-delete-value: 0,
  logic-delete-value: 1
